query Groups {
  groups {
    id
    name
    course {
      id
      name
    }
    teacher {
      lastName
      firstName
      patronymic
    }
    startDate
    studentsCount
  }
}

query GroupsSmallList {
  groups {
    id
    name
    courseId
  }
}