query GroupByID($groupID: Int!, $courseID: Int!) {
  group(id: $groupID) {
    id
    name
    course{
      id
      name
    }
    teacher{
      id
      lastName
      firstName
      patronymic
    }
    studentsCount
  }
  students: students(groupId: $groupID){
    id
    firstName
    lastName
    patronymic
    birthDate
    info {
      courseId
      contractState
      attempt
      group {
        id
      }
    }
  }
  otherStudents: students (groupId: $groupID, courseId: $courseID){
    ...otherStudentsFields
  }
}

query OtherStudentsByCourseId ($courseID: Int!){
  otherStudents: students(courseId: $courseID){
    ...otherStudentsFields
  }
}
fragment otherStudentsFields on StudentType{
  id
  firstName
  lastName
  patronymic
  birthDate
  info {
    courseId
    contractState
    attempt
  }
}