#query GroupByID($groupID: ID!) {
#  group: Group(id: $groupID) {
#    id
#    name
#    course: Course {
#      name
#    }
#    teacher: Teacher {
#      lastName
#      firstName
#      patronymic
#    }
#    students: Infos {
#      Student {
#        id
#        lastName
#        firstName
#        patronymic
#      }
#    }
#  }
#}
query GroupByID($groupID: Int!, $courseID: Int!) {
  group(id: $groupID) {
    id
    name
    course{
      id
      name
    }
    teacher{
      id
      lastName
      firstName
      patronymic
    }
    studentsCount
  }
  students: students(groupId: $groupID){
    id
    firstName
    lastName
    patronymic
    birthDate
  }
  otherStudents: students (groupId: $groupID, courseId: $courseID){
    id
    firstName
    lastName
    patronymic
    birthDate
  }
}