mutation login($user: LoginInput!) {
  login(loginInput: $user) {
    accessToken
    message
    refreshToken
  }
}

mutation renewToken($tokens: RenewTokenInput!){
  relogin: renewAccessToken(renewToken: $tokens) {
    accessToken
    message
    refreshToken
  }
}