## local
#query Student($studentID: ID!) {
#  student: Student(id: $studentID) {
#    id
#    lastName
#    firstName
#    patronymic
#    birthDate
#    school: School {
#      name
#      district
#    }
#    parent: Parent {
#      lastName
#      firstName
#      patronymic
#      phoneNumber
#      secondPhoneNumber
#      email
#      secondEmail
#      applyingDate
#    }
#    info: Infos {
#      admissionDate
#      contractState
#
#      courseId: course_id
#      course: Course {
#        name
#      }
#      group: Group {
#        name
#      }
#
#      isCoursePaid
#      isEquipmentPaid
#      isGetRobot
#    }
#  }
#}


# asp
query Student($studentID: Int!) {
  student(id: $studentID) {
    id
    lastName
    firstName
    patronymic
    birthDate
    school {
      name
      district
    }
    parent {
      lastName
      firstName
      patronymic
      phoneNumber
      secondPhoneNumber
      email
      secondEmail
      applyingDate
    }
    info {
      admissionDate
      contractState

      courseId
      course {
        name
      }
      group {
        name
      }

      isCoursePaid
      isEquipmentPaid
      isGetRobot
    }
  }
}