##local
#query Students {
#  students: allStudents{
#    id
#    lastName
#    patronymic
#    birthDate
#    firstName
#    description
#    parent: Parent {
#      phoneNumber
#      secondPhoneNumber
#      applyingDate
#    }
#    info: Infos {
#      course: Course {
#        name
#      }
#      group: Group {
#        name
#      }
#      isCoursePaid
#      isEquipmentPaid
#      admissionDate
#      contractState
#    }
#  }
#}

#asp
query Students {
  students {
    id
    lastName
    patronymic
    birthDate
    firstName
    description
    parent {
      phoneNumber
      secondPhoneNumber
      applyingDate
    }
    info {
      course {
        name
      }
      group {
        name
      }
      isCoursePaid
      isEquipmentPaid
      admissionDate
      contractState
    }
  }
}