#query Groups {
#  groups: allGroups {
#    id
#    name
#    course: Course {
#      name
#    }
#    teacher: Teacher {
#      lastName
#      firstName
#      patronymic
#    }
#    startDate
#    studentsCount
#  }
#}

query Groups {
  groups {
    id
    name
    course {
      name
    }
    teacher {
      lastName
      firstName
      patronymic
    }
    startDate
    studentsCount
  }
}