query AllStudents {
  students {
    id
    lastName
    firstName
    patronymic
    birthDate
    description
    parent {
      id
      
      firstName
      lastName
      patronymic

      phoneNumber
      secondPhoneNumber

      email
      secondEmail

      applyingDate
    }
    info {
      attempt
      course {
        name
      }
      admissionDate
      contractState
      isCoursePaid
      isEquipmentPaid
    }
  }
}